default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'hoichuphong513'
 
development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

